// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgres

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID
	FirstName sql.NullString
	LastName  sql.NullString
	Nickname  string
	Password  []byte
	Email     string
	Country   sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
